name: CI/CD to Remote Server

on:
  push:
    branches: [dev] # Trigger workflow on push to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup SSH key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Run deployment commands on server
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd Lije-care-mini-app/dev
          git stash || true
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          git pull
          npm install --legacy-peer-deps
          npm run build
          EOF
